### ISSUE TITLE
Running the examples

### ISSUE THREAD

**Issue by AnneMaelle** [LIBOL/SOL#7]
Hello,

I have just installed the Library following the Install wiki. When I try one of the example I have this error : 
```
(pyenv) (C:\Users\abarneche\AppData\Local\Continuum\Anaconda3) C:\Users\abarneche\SOL>sol_train data/a1a a1a.model
Traceback (most recent call last):
  File "C:\Users\abarneche\SOL\pyenv\Scripts\sol_train-script.py", line 11, in <module>
    load_entry_point('sol==1.1.0', 'console_scripts', 'sol_train')()
  File "C:\Users\abarneche\SOL\pyenv\lib\site-packages\pkg_resources\__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\abarneche\SOL\pyenv\lib\site-packages\pkg_resources\__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "C:\Users\abarneche\SOL\pyenv\lib\site-packages\pkg_resources\__init__.py", line 2305, in load
    return self.resolve()
  File "C:\Users\abarneche\SOL\pyenv\lib\site-packages\pkg_resources\__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\abarneche\SOL\pyenv\lib\site-packages\sol-1.1.0-py3.6-win-amd64.egg\sol\__init__.py", line 8, in <module>
    from pysol import SOL
  File "python\pysol.pyx", line 5, in init python.pysol (python/pysol.cpp:8874)
    import numpy as np
SystemError: Parent module 'pysol' not loaded, cannot perform relative import
```

**Comment by AnneMaelle** [comment]
I forgot to mention, I installed the python scripts on Windows

**Comment by yuewu001** [comment]
are u using python3? can you try python2 instead?
