### ISSUE TITLE
run experiment.py for linux

### ISSUE THREAD

**Issue by wuheng199112068** [LIBOL/SOL#8]
When python experiment.py --shufle 10 a1a ../data/a1a ../data/a1a.t, the error
 ImportError: /usr/lib/python3.4/dist-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct
I am sad.
Why?
thank you!

**Comment by wuheng199112068** [comment]
Traceback (most recent call last):
  File "experiment.py", line 12, in <module>
    import numpy as np
  File "/usr/lib/python3.4/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python3.4/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3.4/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3.4/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3.4/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: /usr/lib/python3.4/dist-packages/numpy/core/multiarray.so: undefined symbol: _Py_ZeroStruct

**Comment by wuheng199112068** [comment]
why have this error?thank you.
